#!/bin/sh

echo -e "Welcome to $(lsb_release -s -d) $(hostname) ($(uname -o) $(uname -r) $(uname -m))"
echo -e ""
echo -e "  System information as of $(date)"
echo -e ""
echo -e "  System load:\t$(cat /proc/loadavg | cut -d" " -f1)\t\tProcesses:\t\t$(ps aux | wc -l)"
echo -e "  Usage of /:\t$(df -h / | grep / | awk '{ print $5}') of $(df -h / | grep / | awk '{ print $2}')\tUsers logged in:\t$(users | wc -w)"
echo -e "  Memory usage:\t$(($(free -m | grep Mem | awk '{ print $3}')*100/$(free -m | grep Mem | awk '{ print $2}')))%\t\tIP address for $(cat /proc/net/route | grep 00000000 | awk '{ print $1}' | uniq):\t$(ip addr show $(cat /proc/net/route | grep 00000000 | awk '{ print $1}' | uniq) | grep 'inet ' | awk '{ print $2}' | cut -d/ -f1)"
echo -e "  Swap usage:\t$(($(free -m | grep Swap | awk '{ print $3}')*100/$(free -m | grep Swap | awk '{ print $2}')))%\t\tUptime:\t$(uptime -p)"
if [ -x /opt/vc/bin/vcgencmd ]; then
  echo -e "  Voltage:\t$(/opt/vc/bin/vcgencmd measure_volts | cut -d= -f2)\t\tTemperature:\t\t$(/opt/vc/bin/vcgencmd measure_temp | cut -d= -f2)"
  if [ $(/opt/vc/bin/vcgencmd get_throttled | cut -d= -f2) != "0x0" ]; then
    echo -e ""
    echo -e "    WARNING: CPU is throttled"

  fi
fi
if [ ! -x /usr/bin/lsb_release ]; then
  echo -e ""
  echo -e "Please, install lsb-release package..."
fi
echo -e ""
